apiVersion: wasme.io/v1
kind: FilterDeployment
metadata:
  name: bookinfo-kronos
spec:
  deployment:
    istio:
      kind: Deployment
  filter:
    image: webassemblyhub.io/haggs/secrets-filter:latest