apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasm-secrets-auth-api
  labels:
    app: wasm-secrets-auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasm-secrets-auth-api
  template:
    metadata:
      labels:
        app: wasm-secrets-auth-api
    spec:
      containers:
      - name: wasm-secrets-auth-api
        image: docker.io/blhagadorn/wasm-secrets-auth-api:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: wasm-secrets-auth-api-svc
spec:
  selector:
    app: wasm-secrets-auth-api
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 3000          